import rawParts from "./brainParts.generated.json";
import type { RegionId } from "./regions";

export interface BrainPart {
  nodeName: string;
  englishName: string;
  regionId: RegionId | null;
  centroid: readonly [number, number, number];
}

// Generated by assets/source/build_segmented_brain.py from the BodyParts3D
// dataset (CC BY-SA 2.1 Japan) — one entry per mesh node in public/brain.glb.
export const BRAIN_PARTS: readonly BrainPart[] = rawParts as unknown as BrainPart[];

export const ANATOMICAL_REGION_IDS: ReadonlySet<RegionId> = new Set(
  BRAIN_PARTS.map((part) => part.regionId).filter((id): id is RegionId => id !== null),
);

// Exploded position = centroid * (1 + (EXPLODE_SCALE - 1) * progress).
export const EXPLODE_SCALE = 1.9;

// Regions with no distinct anatomical boundary, hand-mapped to whichever
// real structure(s) have an established correspondence in the literature —
// NOT auto-picked by nearest-centroid distance. That approach was tried and
// discarded: it matched the VTA (midbrain) to the cerebellum, because a raw
// distance search has no notion of which structures are actually related.
// Several of these are genuinely multi-piece complexes, not one structure —
// highlighting all of them together is exactly what nodeNamesForRegion and
// BrainMesh already support (it's how bilateral pairs like Amygdala work).
const FUNCTIONAL_REGION_PART_IDS: Partial<Record<RegionId, readonly string[]>> = {
  // Orbital gyri (OFC proper) + straight gyrus/gyrus rectus. vmPFC and OFC
  // sharing this piece is correct, not a shortcut — this app's own research
  // notes say medial OFC and vmPFC are "largely the same territory... used
  // interchangeably." There is no other piece in this dataset that is
  // actually vmPFC's rather than DLPFC's or SMA's, so it can't honestly be
  // made any bigger than this.
  vmPFC: ["BP51"],
  OFC: ["BP51"],
  DLPFC: ["FMA72655", "FMA72656"], // right/left middle frontal gyrus — the standard correspondence
  // Classic multi-gyrus TPJ complex: angular + supramarginal gyrus, plus
  // the posterior superior temporal gyrus/sulcus.
  TPJ: ["FMA72669", "FMA72670", "FMA72667", "FMA72668", "FMA72804", "FMA72805"],
  // Right/left superior frontal gyrus — pre-SMA/SMA's real location is the
  // posterior-medial surface of this gyrus specifically. This dataset
  // doesn't split the gyrus into medial (SMA) vs lateral parts, but this is
  // SMA's territory, not vmPFC's — it used to be double-booked between the
  // two, which was exactly the confusing overlap this comment is now here
  // to prevent from coming back.
  SMA: ["FMA72653", "FMA72654"],
  VTA: ["FMA61993nsn", "FMA62394"], // midbrain + its peduncle — both genuinely midbrain, unclaimed elsewhere
  // Ventral striatum is anatomically continuous with both — not just putamen.
  NAcc: ["FMA72828", "FMA72829", "FMA72826", "FMA72827"],
};

export function nodeNamesForRegion(regionId: RegionId): readonly string[] {
  if (ANATOMICAL_REGION_IDS.has(regionId)) {
    return BRAIN_PARTS.filter((part) => part.regionId === regionId).map((part) => part.nodeName);
  }
  return FUNCTIONAL_REGION_PART_IDS[regionId] ?? [];
}

// A piece can legitimately belong to more than one region's forward mapping
// (BP51 is shared by vmPFC and OFC, which really do overlap) — sidebar
// selection handles that fine via nodeNamesForRegion. Direct 3D clicks
// can't: this map can only hold one region per node, so a shared piece
// resolves to whichever region is defined later above.
const NODE_TO_FUNCTIONAL_REGION = new Map<string, RegionId>(
  (Object.entries(FUNCTIONAL_REGION_PART_IDS) as [RegionId, readonly string[]][]).flatMap(
    ([regionId, nodeNames]) => nodeNames.map((nodeName) => [nodeName, regionId] as const),
  ),
);

const NODE_TO_PART = new Map(BRAIN_PARTS.map((part) => [part.nodeName, part]));

export function regionIdForNode(nodeName: string): RegionId | null {
  const anatomicalRegionId = NODE_TO_PART.get(nodeName)?.regionId;
  return anatomicalRegionId ?? NODE_TO_FUNCTIONAL_REGION.get(nodeName) ?? null;
}

export function regionCentroid(regionId: RegionId): readonly [number, number, number] | null {
  const centroids = nodeNamesForRegion(regionId)
    .map((nodeName) => NODE_TO_PART.get(nodeName)?.centroid)
    .filter((centroid): centroid is readonly [number, number, number] => centroid !== undefined);

  if (centroids.length === 0) return null;

  const sum = centroids.reduce((acc, [x, y, z]) => [acc[0] + x, acc[1] + y, acc[2] + z], [0, 0, 0]);
  return [sum[0] / centroids.length, sum[1] / centroids.length, sum[2] / centroids.length];
}
